zcat /net/tinker/rhadidi6/DPC2/traces/milc_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_ampm | tee /net/tinker/rhadidi6/DPC2/results/ampm_milc
zcat /net/tinker/rhadidi6/DPC2/traces/lbm_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_ampm | tee /net/tinker/rhadidi6/DPC2/results/ampm_lbm
zcat /net/tinker/rhadidi6/DPC2/traces/gcc_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_ampm | tee /net/tinker/rhadidi6/DPC2/results/ampm_gcc
zcat /net/tinker/rhadidi6/DPC2/traces/leslie3d_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_ampm | tee /net/tinker/rhadidi6/DPC2/results/ampm_leslie3d
zcat /net/tinker/rhadidi6/DPC2/traces/libquantum_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_ampm | tee /net/tinker/rhadidi6/DPC2/results/ampm_libquantum
zcat /net/tinker/rhadidi6/DPC2/traces/GemsFDTD_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_ampm | tee /net/tinker/rhadidi6/DPC2/results/ampm_GemsFDTD
zcat /net/tinker/rhadidi6/DPC2/traces/omnetpp_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_ampm | tee /net/tinker/rhadidi6/DPC2/results/ampm_omnetpp
zcat /net/tinker/rhadidi6/DPC2/traces/mcf_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_ampm | tee /net/tinker/rhadidi6/DPC2/results/ampm_mcf
zcat /net/tinker/rhadidi6/DPC2/traces/milc_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_ip | tee /net/tinker/rhadidi6/DPC2/results/ip_milc
zcat /net/tinker/rhadidi6/DPC2/traces/lbm_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_ip | tee /net/tinker/rhadidi6/DPC2/results/ip_lbm
zcat /net/tinker/rhadidi6/DPC2/traces/gcc_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_ip | tee /net/tinker/rhadidi6/DPC2/results/ip_gcc
zcat /net/tinker/rhadidi6/DPC2/traces/leslie3d_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_ip | tee /net/tinker/rhadidi6/DPC2/results/ip_leslie3d
zcat /net/tinker/rhadidi6/DPC2/traces/libquantum_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_ip | tee /net/tinker/rhadidi6/DPC2/results/ip_libquantum
zcat /net/tinker/rhadidi6/DPC2/traces/GemsFDTD_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_ip | tee /net/tinker/rhadidi6/DPC2/results/ip_GemsFDTD
zcat /net/tinker/rhadidi6/DPC2/traces/omnetpp_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_ip | tee /net/tinker/rhadidi6/DPC2/results/ip_omnetpp
zcat /net/tinker/rhadidi6/DPC2/traces/mcf_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_ip | tee /net/tinker/rhadidi6/DPC2/results/ip_mcf
zcat /net/tinker/rhadidi6/DPC2/traces/milc_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_nl | tee /net/tinker/rhadidi6/DPC2/results/nl_milc
zcat /net/tinker/rhadidi6/DPC2/traces/lbm_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_nl | tee /net/tinker/rhadidi6/DPC2/results/nl_lbm
zcat /net/tinker/rhadidi6/DPC2/traces/gcc_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_nl | tee /net/tinker/rhadidi6/DPC2/results/nl_gcc
zcat /net/tinker/rhadidi6/DPC2/traces/leslie3d_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_nl | tee /net/tinker/rhadidi6/DPC2/results/nl_leslie3d
zcat /net/tinker/rhadidi6/DPC2/traces/libquantum_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_nl | tee /net/tinker/rhadidi6/DPC2/results/nl_libquantum
zcat /net/tinker/rhadidi6/DPC2/traces/GemsFDTD_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_nl | tee /net/tinker/rhadidi6/DPC2/results/nl_GemsFDTD
zcat /net/tinker/rhadidi6/DPC2/traces/omnetpp_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_nl | tee /net/tinker/rhadidi6/DPC2/results/nl_omnetpp
zcat /net/tinker/rhadidi6/DPC2/traces/mcf_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_nl | tee /net/tinker/rhadidi6/DPC2/results/nl_mcf
zcat /net/tinker/rhadidi6/DPC2/traces/milc_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_stream | tee /net/tinker/rhadidi6/DPC2/results/stream_milc
zcat /net/tinker/rhadidi6/DPC2/traces/lbm_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_stream | tee /net/tinker/rhadidi6/DPC2/results/stream_lbm
zcat /net/tinker/rhadidi6/DPC2/traces/gcc_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_stream | tee /net/tinker/rhadidi6/DPC2/results/stream_gcc
zcat /net/tinker/rhadidi6/DPC2/traces/leslie3d_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_stream | tee /net/tinker/rhadidi6/DPC2/results/stream_leslie3d
zcat /net/tinker/rhadidi6/DPC2/traces/libquantum_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_stream | tee /net/tinker/rhadidi6/DPC2/results/stream_libquantum
zcat /net/tinker/rhadidi6/DPC2/traces/GemsFDTD_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_stream | tee /net/tinker/rhadidi6/DPC2/results/stream_GemsFDTD
zcat /net/tinker/rhadidi6/DPC2/traces/omnetpp_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_stream | tee /net/tinker/rhadidi6/DPC2/results/stream_omnetpp
zcat /net/tinker/rhadidi6/DPC2/traces/mcf_trace2.dpc.gz | /net/tinker/rhadidi6/DPC2/dpc2sim_stream | tee /net/tinker/rhadidi6/DPC2/results/stream_mcf
